"use client"

import React from "react"
import Link from "next/link"
import { Download, IndianRupee, Users, Stethoscope, Pill, FlaskConical, Scan, Calendar, TrendingUp, BarChart3, PieChart, FileText } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"

const reportTypes = [
  { id: "revenue", title: "Revenue Report", description: "Daily, weekly, and monthly revenue analytics", icon: IndianRupee, color: "blue", href: "/reports/revenue" },
  { id: "patients", title: "Patient Report", description: "Patient registration, discharge, and demographics", icon: Users, color: "green", href: "/reports/patients" },
  { id: "doctors", title: "Doctor Report", description: "Doctor performance and consultation analytics", icon: Stethoscope, color: "purple", href: "/reports/doctors" },
  { id: "pharmacy", title: "Pharmacy Report", description: "Medicine sales, inventory, and purchase analytics", icon: Pill, color: "yellow", href: "/reports/pharmacy" },
  { id: "pathology", title: "Pathology Report", description: "Lab tests conducted, results, and turnaround time", icon: FlaskConical, color: "red", href: "/reports/pathology" },
  { id: "radiology", title: "Radiology Report", description: "Imaging studies and diagnostic analytics", icon: Scan, color: "indigo", href: "/reports/radiology" },
  { id: "appointments", title: "Appointment Report", description: "Appointment scheduling and attendance analytics", icon: Calendar, color: "teal", href: "/reports/appointments" },
  { id: "billing", title: "Billing Report", description: "Invoice generation, payments, and dues analytics", icon: FileText, color: "orange", href: "/reports/billing" },
]

const recentReports = [
  { id: "RPT001", reportName: "Daily Revenue Summary", generatedBy: "System", date: "2026-08-07", type: "Revenue", status: "Ready" },
  { id: "RPT002", reportName: "Patient Discharge Report", generatedBy: "Dr. Priya Sharma", date: "2026-08-07", type: "Patient", status: "Ready" },
  { id: "RPT003", reportName: "Pharmacy Sales Report", generatedBy: "Sanjay Mehta", date: "2026-08-06", type: "Pharmacy", status: "Ready" },
  { id: "RPT004", reportName: "Weekly Lab Tests Summary", generatedBy: "System", date: "2026-08-05", type: "Pathology", status: "Ready" },
  { id: "RPT005", reportName: "Monthly Payroll Report", generatedBy: "Rahul Joshi", date: "2026-08-01", type: "HR", status: "Ready" },
]

const colorMap: Record<string, string> = {
  blue: "bg-blue-100 text-blue-600",
  green: "bg-green-100 text-green-600",
  purple: "bg-purple-100 text-purple-600",
  yellow: "bg-yellow-100 text-yellow-600",
  red: "bg-red-100 text-red-600",
  indigo: "bg-indigo-100 text-indigo-600",
  teal: "bg-teal-100 text-teal-600",
  orange: "bg-orange-100 text-orange-600",
}

export default function ReportsPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Reports & Analytics</h1>
          <p className="text-slate-500">Generate and view hospital analytics reports</p>
        </div>
        <Button variant="outline" size="sm"><Download className="mr-2 h-4 w-4" />Export All</Button>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {reportTypes.map((report) => (
          <Link key={report.id} href={report.href}>
            <Card className="hover:shadow-md transition-shadow cursor-pointer">
              <CardContent className="p-4">
                <div className="flex items-start gap-3">
                  <div className={`rounded-lg p-2 ${colorMap[report.color]}`}>
                    <report.icon className="h-5 w-5" />
                  </div>
                  <div>
                    <h3 className="font-semibold">{report.title}</h3>
                    <p className="text-xs text-slate-500 mt-1">{report.description}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Recently Generated Reports</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {recentReports.map((report) => (
              <div key={report.id} className="flex items-center justify-between rounded-lg border p-4">
                <div className="flex items-center gap-3">
                  <div className="rounded-lg bg-slate-100 p-2">
                    <BarChart3 className="h-4 w-4 text-slate-600" />
                  </div>
                  <div>
                    <p className="font-medium">{report.reportName}</p>
                    <p className="text-xs text-slate-500">Generated by {report.generatedBy} on {report.date}</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <Badge variant="outline">{report.type}</Badge>
                  <Badge variant="success">{report.status}</Badge>
                  <Button variant="ghost" size="sm"><Download className="h-4 w-4" /></Button>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
